For the maximal location covering problem, we can set up our problem very similarly to before.

In [1]:
from lokigi.site import SiteProblem
import pandas as pd

problem = SiteProblem()

problem.add_sites(
    "../../../sample_data/brighton_sites_named.geojson",
    candidate_id_col="site"
    )

problem.add_travel_matrix(
    travel_matrix_df="../../../sample_data/brighton_travel_matrix_driving_named.csv",
    source_col="LSOA",
    from_unit="seconds",
    to_unit="minutes"
    )

problem.add_region_geometry_layer(
    "https://github.com/hsma-programme/h6_3d_facility_location_problems/raw/refs/heads/main/h6_3d_facility_location_problems/example_code/LSOA_2011_Boundaries_Super_Generalised_Clipped_BSC_EW_V4.geojson",
    common_col="LSOA11NM"
    )

In [2]:
solutions = problem.solve(objectives="mclp", p=3, threshold_for_coverage=10)

C:\lokigi\lokigi\site.py:575: UserWarning: No demand data was provided. Demand from all regions has been assumed to be equal.If you wish to override this, run .add_demand() to add your site dataframe before running .solve() again.You can use the .show_demand_format() to see the expected format beforehand.
  warn(

In [3]:
solutions.show_solutions()

,site_names,site_indices,weighted_average,unweighted_average,90th_percentile,max,proportion_within_coverage_threshold,problem_df
0,None,"[2, 3, 5]",5.36,5.36,8.06,16.69,0.95,LSOA L...
1,None,"[2, 3, 4]",5.45,5.45,8.50,16.69,0.95,LSOA L...
2,None,"[1, 2, 3]",5.59,5.59,9.00,16.69,0.94,LSOA L...
3,None,"[0, 2, 5]",6.21,6.21,9.33,16.69,0.94,LSOA L...
4,None,"[0, 2, 3]",5.67,5.67,9.36,16.69,0.93,LSOA L...
5,None,"[2, 4, 5]",6.29,6.29,9.26,16.69,0.93,LSOA L...
6,None,"[1, 2, 5]",6.31,6.31,9.45,16.69,0.92,LSOA L...
7,None,"[0, 2, 4]",6.32,6.32,9.70,16.69,0.91,LSOA L...
8,None,"[0, 1, 2]",6.39,6.39,9.77,16.69,0.91,LSOA L...
9,None,"[1, 3, 4]",6.76,6.76,11.32,21.71,0.83,LSOA L...
10,None,"[1, 3, 5]",6.64,6.64,11.58,22.86,0.81,LSOA L...
11,None,"[1, 4, 5]",7.65,7.65,11.67,21.71,0.81,LSOA L...
12,None,"[3, 4, 5]",6.73,6.73,12.26,21.71,0.80,LSOA L...
13,None,"[0, 3, 4]",6.81,6.81,12.26,21.71,0.80,LSOA L...
14,None,"[0, 1, 3]",6.92,6.92,11.93,23.92,0.80,LSOA L...
15,None,"[0, 1, 5]",7.54,7.54,11.90,22.86,0.79,LSOA L...
16,None,"[0, 1, 4]",7.66,7.66,11.67,21.71,0.79,LSOA L...
17,None,"[0, 4, 5]",7.70,7.70,12.65,21.71,0.78,LSOA L...
18,None,"[1, 2, 4]",7.46,7.46,11.57,16.69,0.72,LSOA L...
19,None,"[0, 3, 5]",7.69,7.69,13.72,22.86,0.67,LSOA L...

In [4]:
solutions.show_solutions()["problem_df"][0]

,LSOA,LSOA_x,Tulip (Site 3),Daisy (Site 4),Snowdrop (Site 6),min_cost,selected_site,within_threshold,LSOA_y,n
0,Brighton and Hove 027E,Brighton and Hove 027E,7.404833,8.197500,9.248500,7.404833,Tulip (Site 3),True,Brighton and Hove 027E,1
1,Brighton and Hove 027F,Brighton and Hove 027F,8.626167,9.351167,8.972833,8.626167,Tulip (Site 3),True,Brighton and Hove 027F,1
2,Brighton and Hove 027A,Brighton and Hove 027A,8.633000,6.840000,9.289167,6.840000,Daisy (Site 4),True,Brighton and Hove 027A,1
3,Brighton and Hove 029E,Brighton and Hove 029E,11.006000,6.328667,9.293000,6.328667,Daisy (Site 4),True,Brighton and Hove 029E,1
4,Brighton and Hove 029D,Brighton and Hove 029D,10.970000,5.216667,9.508500,5.216667,Daisy (Site 4),True,Brighton and Hove 029D,1
...,...,...,...,...,...,...,...,...,...,...
160,Brighton and Hove 012A,Brighton and Hove 012A,18.468500,8.652667,7.463000,7.463000,Snowdrop (Site 6),True,Brighton and Hove 012A,1
161,Brighton and Hove 005C,Brighton and Hove 005C,16.804000,9.490000,5.798500,5.798500,Snowdrop (Site 6),True,Brighton and Hove 005C,1
162,Brighton and Hove 012B,Brighton and Hove 012B,18.876667,8.952500,7.871000,7.871000,Snowdrop (Site 6),True,Brighton and Hove 012B,1
163,Brighton and Hove 005A,Brighton and Hove 005A,18.432167,11.068500,7.426667,7.426667,Snowdrop (Site 6),True,Brighton and Hove 005A,1
164,Brighton and Hove 005B,Brighton and Hove 005B,17.232333,9.918333,6.226833,6.226833,Snowdrop (Site 6),True,Brighton and Hove 005B,1